{% set name = "pdf2image" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eaa959bc116b420dd7ec415fcae49b98100dda3dd18cd2fdfa86d09f112f6d57

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pillow
    - poppler

test:
  imports:
    - pdf2image
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/Belval/pdf2image
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A wrapper around the pdftoppm and pdftocairo command line tools to convert PDF to a PIL Image list.

extra:
  recipe-maintainers:
    - mxr-conda
    - benhuff
    - oblute
    - rluria14
    - m-rossi
